/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.admin;

import models.QuanLyThongKeController;

/**
 *
 * @author hoang
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel() {
        initComponents();
        
        QuanLyThongKeController controller = new QuanLyThongKeController();
        controller.setDataToChart1(Bieudocot);
        controller.setDataToChart2(Bieudotron);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Handle.PanelRound();
        Bieudocot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Bieudotron = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout(100, 50));

        panelRound1.setLayout(new javax.swing.BoxLayout(panelRound1, javax.swing.BoxLayout.Y_AXIS));

        Bieudocot.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BieudocotLayout = new javax.swing.GroupLayout(Bieudocot);
        Bieudocot.setLayout(BieudocotLayout);
        BieudocotLayout.setHorizontalGroup(
            BieudocotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        BieudocotLayout.setVerticalGroup(
            BieudocotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelRound1.add(Bieudocot);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        panelRound1.add(jPanel1);

        Bieudotron.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BieudotronLayout = new javax.swing.GroupLayout(Bieudotron);
        Bieudotron.setLayout(BieudotronLayout);
        BieudotronLayout.setHorizontalGroup(
            BieudotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BieudotronLayout.setVerticalGroup(
            BieudotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelRound1.add(Bieudotron);

        add(panelRound1, "card2");

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bieudocot;
    private javax.swing.JPanel Bieudotron;
    private javax.swing.JPanel jPanel1;
    private Handle.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
