/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.user;
import Handle.PanelRound;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import models.*;
import views.admin.*;
import javax.swing.*;
import javax.swing.JPasswordField;


/**
 *
 * @author ADMIN
 */
public class changingPassword extends javax.swing.JDialog {
    private User getUser;
    private Student student;
    private boolean status = false;

    public boolean getStatus() {
        return status;
    }

    
    
    /**
     * Creates new form changingPassword
     */
    public changingPassword(java.awt.Frame parent, boolean modal, Student std) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        student = std;
        getUser = new UserDAO().getUser(std.getId());
    }
    
    public changingPassword(java.awt.Frame parent, boolean modal) {
        
    }
    
    public void animationClick (PanelRound panel, String beforeColor) {
        panel.setBackground(new Color(221, 242, 253, 128));
        Timer timer = new Timer(250, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.setBackground(Color.decode(beforeColor));
                ((Timer) e.getSource()).stop();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Handle.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        roundPanel = new Handle.PanelRound();
        okButton = new Handle.PanelRound();
        okLabel = new javax.swing.JLabel();
        cancelButton = new Handle.PanelRound();
        panelRound4 = new Handle.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        panelRound3 = new Handle.PanelRound();
        panelRound2 = new Handle.PanelRound();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputOldPasword = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputNewPassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reinputNewPassword = new javax.swing.JPasswordField();
        showWrongPassword = new javax.swing.JLabel();
        showWrongReinput = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(35, 45, 63));
        jPanel1.setLayout(new java.awt.CardLayout(5, 5));

        jPanel3.setBackground(new java.awt.Color(35, 45, 63));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(35, 45, 63));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(35, 45, 63));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        roundPanel.setEnabled(false);
        roundPanel.setPreferredSize(new java.awt.Dimension(80, 40));
        roundPanel.setRoundBottomLeft(20);
        roundPanel.setRoundBottomRight(20);
        roundPanel.setRoundTopLeft(20);
        roundPanel.setRoundTopRight(20);
        roundPanel.setLayout(new java.awt.CardLayout(5, 5));

        okButton.setBackground(new java.awt.Color(35, 45, 63));
        okButton.setEnabled(false);
        okButton.setRoundBottomLeft(10);
        okButton.setRoundBottomRight(10);
        okButton.setRoundTopLeft(10);
        okButton.setRoundTopRight(10);
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        okButton.setLayout(new java.awt.CardLayout());

        okLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        okLabel.setForeground(new java.awt.Color(255, 255, 255));
        okLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okLabel.setText("OK");
        okLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okLabel.setEnabled(false);
        okButton.add(okLabel, "card2");

        roundPanel.add(okButton, "card2");

        jPanel4.add(roundPanel);

        cancelButton.setPreferredSize(new java.awt.Dimension(80, 40));
        cancelButton.setRoundBottomLeft(20);
        cancelButton.setRoundBottomRight(20);
        cancelButton.setRoundTopLeft(20);
        cancelButton.setRoundTopRight(20);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.setLayout(new java.awt.CardLayout(5, 5));

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new java.awt.CardLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hủy");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound4.add(jLabel6, "card2");

        cancelButton.add(panelRound4, "card2");

        jPanel4.add(cancelButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new java.awt.CardLayout());

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mật khẩu cũ:");
        jPanel5.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        inputOldPasword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputOldPasword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        inputOldPasword.setOpaque(true);
        inputOldPasword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputOldPaswordKeyReleased(evt);
            }
        });
        jPanel5.add(inputOldPasword, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mật khẩu mới:");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        inputNewPassword.setEditable(false);
        inputNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        inputNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNewPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        inputNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNewPasswordKeyReleased(evt);
            }
        });
        jPanel6.add(inputNewPassword, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu mới:");
        jPanel7.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        reinputNewPassword.setEditable(false);
        reinputNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        reinputNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reinputNewPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        reinputNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reinputNewPasswordKeyReleased(evt);
            }
        });
        jPanel7.add(reinputNewPassword, java.awt.BorderLayout.CENTER);

        showWrongPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showWrongPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showWrongPassword.setText("  ");

        showWrongReinput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showWrongReinput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showPassword.setText("Hiển thị mật khẩu");
        showPassword.setBorder(null);
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showWrongReinput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showWrongPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showWrongPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showWrongReinput, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassword)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelRound3.add(panelRound2, "card2");

        jPanel3.add(panelRound3, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel3, "card2");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        animationClick(panelRound4, "#cccccc");
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        char[] reinputNewPass = reinputNewPassword.getPassword();
        String reinputNewPassword = new String(reinputNewPass);
        if (okLabel.isEnabled()){
            animationClick(okButton, "#232d3f");
            User updatedUser = new User();
            updatedUser.setUsername(getUser.getUsername());
            updatedUser.setPassword(reinputNewPassword);
            updatedUser.setIsAdmin(false);
            UserDAO updatePassword = new UserDAO();
            if (updatePassword.updateUser(updatedUser)){
                showWrongReinput.setText("Cập nhật thành công!");
                showWrongReinput.setForeground(Color.decode("#219C90"));
            }
            Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Ẩn dialog
                dispose();
                }
            });
            timer.start();
        }
    }//GEN-LAST:event_okButtonMouseClicked

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if(showPassword.isSelected()){
            inputOldPasword.setEchoChar((char) 0);
            inputNewPassword.setEchoChar((char) 0);
            reinputNewPassword.setEchoChar((char) 0);
        } else {
            inputOldPasword.setEchoChar('*');
            inputNewPassword.setEchoChar('*');
            reinputNewPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void inputOldPaswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputOldPaswordKeyReleased
        // TODO add your handling code here:
        char[] passwordChars = inputOldPasword.getPassword();
        String password = new String(passwordChars);
        if (!(password.equals(getUser.getPassword()))){
            showWrongPassword.setText("*Mật khẩu không đúng !");
            showWrongPassword.setForeground(Color.decode("#F05941"));
            inputNewPassword.setEditable(false);
            reinputNewPassword.setEditable(false);
        } else {
            showWrongPassword.setText("");
            inputNewPassword.setEditable(true);
            reinputNewPassword.setEditable(true);
        }
    }//GEN-LAST:event_inputOldPaswordKeyReleased

    private void reinputNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reinputNewPasswordKeyReleased
        // TODO add your handling code here:
        char[] newPass = inputNewPassword.getPassword();
        String newPassword = new String(newPass);
       
        char[] reinputNewPass = reinputNewPassword.getPassword();
        String reinputNewPassword = new String(reinputNewPass);
        
        if (!(newPassword.equals(reinputNewPassword))){
            showWrongReinput.setText("*Mật khẩu mới không khớp !");
            showWrongReinput.setForeground(Color.decode("#F05941"));
            okLabel.setEnabled(false);
        }
        
        else {
            showWrongReinput.setText("");
            okLabel.setEnabled(true);
        }
    }//GEN-LAST:event_reinputNewPasswordKeyReleased

    private void inputNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNewPasswordKeyReleased
        // TODO add your handling code here:
        char[] newPass = inputNewPassword.getPassword();
        String newPassword = new String(newPass);
        if (newPassword.length() < 5){
            showWrongReinput.setText("*Mật khẩu phải có từ 5 kí tự!");
            showWrongReinput.setForeground(Color.decode("#F05941"));
            okLabel.setEnabled(false);
        } else {
           showWrongReinput.setText("");
           reinputNewPassword.setEditable(true);
        }
    }//GEN-LAST:event_inputNewPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changingPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changingPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changingPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changingPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changingPassword dialog = new changingPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Handle.PanelRound cancelButton;
    private javax.swing.JPasswordField inputNewPassword;
    private javax.swing.JPasswordField inputOldPasword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private Handle.PanelRound okButton;
    private javax.swing.JLabel okLabel;
    private Handle.PanelRound panelRound1;
    private Handle.PanelRound panelRound2;
    private Handle.PanelRound panelRound3;
    private Handle.PanelRound panelRound4;
    private javax.swing.JPasswordField reinputNewPassword;
    private Handle.PanelRound roundPanel;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel showWrongPassword;
    private javax.swing.JLabel showWrongReinput;
    // End of variables declaration//GEN-END:variables
}
