/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.user;
import Handle.PanelRound;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import models.*;
import views.Login.Login;

/**
 *
 * @author ADMIN
 */
public class myProfile extends javax.swing.JDialog {
    private Student student;

    public void setStudent(Student student) {
        this.student = student;
    }

    public Student getStudent() {
        return student;
    }
    
    
    /**
     * Creates new form myProfile
     */
    public myProfile(java.awt.Frame parent, boolean modal, Student std) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        student = std;
        showProfile();
    }

    public myProfile(java.awt.Frame parent, boolean modal) {
    }

    
    
    public void showProfile(){
        System.out.println("Username my profile: " + student.getId());
        Student std = new UserDAO().getUserProfile(student.getId());
        showName.setText(std.getName());
        showID.setText(std.getId());
        showClass.setText(std.getClassName());
        showGender.setText(std.whichGender());
        showAddress.setText(std.getAddress());
        showBirthday.setText(std.getBirthday());
        showEmail.setText(std.getEmail());
        showPhoneNumber.setText(std.getPhoneNumber());
    }
    public void animationClick (PanelRound panel, String beforeColor) {
        panel.setBackground(new Color(221, 242, 253, 128));
        Timer timer = new Timer(250, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.setBackground(Color.decode(beforeColor));
                ((Timer) e.getSource()).stop();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updateProfileButton = new Handle.PanelRound();
        panelRound5 = new Handle.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        changingPasswordButton = new Handle.PanelRound();
        panelRound8 = new Handle.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        panelRound1 = new Handle.PanelRound();
        panelRound2 = new Handle.PanelRound();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        showID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        showClass = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        showGender = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        showBirthday = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        showAddress = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        showEmail = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        showPhoneNumber = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(35, 45, 63));
        jPanel1.setLayout(new java.awt.CardLayout(5, 5));

        jPanel3.setBackground(new java.awt.Color(35, 45, 63));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(35, 45, 63));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN CỦA BẠN");
        jPanel2.add(jLabel1);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(35, 45, 63));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 5));

        updateProfileButton.setBackground(new java.awt.Color(255, 255, 255));
        updateProfileButton.setRoundBottomLeft(20);
        updateProfileButton.setRoundBottomRight(20);
        updateProfileButton.setRoundTopLeft(20);
        updateProfileButton.setRoundTopRight(20);
        updateProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileButtonMouseClicked(evt);
            }
        });

        panelRound5.setBackground(new java.awt.Color(35, 45, 63));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sửa thông tin");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound5.add(jLabel10);

        updateProfileButton.add(panelRound5);

        jPanel4.add(updateProfileButton);

        changingPasswordButton.setBackground(new java.awt.Color(255, 255, 255));
        changingPasswordButton.setRoundBottomLeft(20);
        changingPasswordButton.setRoundBottomRight(20);
        changingPasswordButton.setRoundTopLeft(20);
        changingPasswordButton.setRoundTopRight(20);
        changingPasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changingPasswordButtonMouseClicked(evt);
            }
        });

        panelRound8.setBackground(new java.awt.Color(35, 45, 63));
        panelRound8.setRoundBottomLeft(10);
        panelRound8.setRoundBottomRight(10);
        panelRound8.setRoundTopLeft(10);
        panelRound8.setRoundTopRight(10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đổi mật khẩu");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound8.add(jLabel11);

        changingPasswordButton.add(panelRound8);

        jPanel4.add(changingPasswordButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Họ tên:");
        jPanel5.add(jLabel2, java.awt.BorderLayout.LINE_START);

        showName.setEditable(false);
        showName.setBackground(new java.awt.Color(255, 255, 255));
        showName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showName.setBorder(null);
        showName.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel5.add(showName, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("MSSV:");
        jPanel6.add(jLabel3, java.awt.BorderLayout.LINE_START);

        showID.setEditable(false);
        showID.setBackground(new java.awt.Color(255, 255, 255));
        showID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showID.setBorder(null);
        showID.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel6.add(showID, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Lớp:");
        jPanel7.add(jLabel4, java.awt.BorderLayout.LINE_START);

        showClass.setEditable(false);
        showClass.setBackground(new java.awt.Color(255, 255, 255));
        showClass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showClass.setBorder(null);
        showClass.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel7.add(showClass, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Giới tính:");
        jPanel8.add(jLabel6, java.awt.BorderLayout.LINE_START);

        showGender.setEditable(false);
        showGender.setBackground(new java.awt.Color(255, 255, 255));
        showGender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showGender.setBorder(null);
        showGender.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel8.add(showGender, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Ngày sinh:");
        jPanel10.add(jLabel5, java.awt.BorderLayout.LINE_START);

        showBirthday.setEditable(false);
        showBirthday.setBackground(new java.awt.Color(255, 255, 255));
        showBirthday.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showBirthday.setBorder(null);
        showBirthday.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel10.add(showBirthday, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel10);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Địa chỉ:");
        jPanel9.add(jLabel7, java.awt.BorderLayout.LINE_START);

        showAddress.setEditable(false);
        showAddress.setBackground(new java.awt.Color(255, 255, 255));
        showAddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showAddress.setBorder(null);
        showAddress.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel9.add(showAddress, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel9);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Email:");
        jPanel12.add(jLabel8, java.awt.BorderLayout.LINE_START);

        showEmail.setEditable(false);
        showEmail.setBackground(new java.awt.Color(255, 255, 255));
        showEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showEmail.setBorder(null);
        showEmail.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel12.add(showEmail, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.BorderLayout(20, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("SĐT:");
        jPanel11.add(jLabel9, java.awt.BorderLayout.LINE_START);

        showPhoneNumber.setEditable(false);
        showPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        showPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showPhoneNumber.setBorder(null);
        showPhoneNumber.setPreferredSize(new java.awt.Dimension(250, 31));
        jPanel11.add(showPhoneNumber, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel11);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(panelRound1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, "card2");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileButtonMouseClicked
        // TODO add your handling code here:
        animationClick(panelRound5, "#232d3f");
        updateProfile udProfile = new updateProfile(null, true, student);
        udProfile.setVisible(true);
        showProfile();
    }//GEN-LAST:event_updateProfileButtonMouseClicked

    private void changingPasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changingPasswordButtonMouseClicked
        // TODO add your handling code here:
        animationClick(panelRound8, "#232D3F");
        changingPassword changePassword = new changingPassword(null, true, student);
        changePassword.setVisible(true);
    }//GEN-LAST:event_changingPasswordButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                myProfile dialog = new myProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Handle.PanelRound changingPasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private Handle.PanelRound panelRound1;
    private Handle.PanelRound panelRound2;
    private Handle.PanelRound panelRound5;
    private Handle.PanelRound panelRound8;
    private javax.swing.JTextField showAddress;
    private javax.swing.JTextField showBirthday;
    private javax.swing.JTextField showClass;
    private javax.swing.JTextField showEmail;
    private javax.swing.JTextField showGender;
    private javax.swing.JTextField showID;
    private javax.swing.JTextField showName;
    private javax.swing.JTextField showPhoneNumber;
    private Handle.PanelRound updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
