/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.Login;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.Timer;
import models.Student;
import models.StudentDAO;
import models.User;
import models.UserDAO;

/**
 *
 * @author ADMIN
 */
public class SignupDialog extends javax.swing.JDialog {

    /**
     * Creates new form signupDialog
     */
    public SignupDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        try {
            GregorianCalendar cal = (GregorianCalendar)GregorianCalendar.getInstance();
            // set the min date
            cal.set(1999, 1, 1);
            GregorianCalendar calmax = (GregorianCalendar)GregorianCalendar.getInstance();
            // set the max date
            calmax.set(2005, 12, 18);
            birthField.setSelectableDateRange( cal.getTime(),calmax.getTime());
            birthField.setDate(new SimpleDateFormat("dd/MM/yyyy").parse("1/1/2000"));
        } catch (Exception e) {
        }
         
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRound7 = new Handle.PanelRound();
        panelRound1 = new Handle.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelRound3 = new Handle.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound4 = new Handle.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        panelRound6 = new Handle.PanelRound();
        panelRound2 = new Handle.PanelRound();
        jPanel14 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        warnLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        showPassword = new javax.swing.JCheckBox();
        panelRound9 = new Handle.PanelRound();
        panelRound5 = new Handle.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        classField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        msvField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        birthField = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelRound7.setBackground(new java.awt.Color(35, 45, 63));
        panelRound7.setPreferredSize(new java.awt.Dimension(958, 290));
        panelRound7.setLayout(new java.awt.CardLayout(5, 5));

        panelRound1.setBackground(new java.awt.Color(35, 45, 63));
        panelRound1.setPreferredSize(new java.awt.Dimension(380, 560));
        panelRound1.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO TÀI KHOẢN");
        panelRound1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(35, 45, 63));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setPreferredSize(new java.awt.Dimension(80, 40));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound3MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tạo");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelRound3);

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setPreferredSize(new java.awt.Dimension(80, 40));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);
        panelRound4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound4MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hủy");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(panelRound4);

        panelRound1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setPreferredSize(new java.awt.Dimension(300, 535));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);
        panelRound6.setLayout(new java.awt.CardLayout(5, 5));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new java.awt.CardLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        warnLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warnLabel.setForeground(new java.awt.Color(240, 89, 65));
        warnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warnLabel.setText("*Đảm bảo thông tin bạn cung cấp là chính xác");
        jPanel1.add(warnLabel);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setMinimumSize(new java.awt.Dimension(40, 20));
        jPanel15.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15);

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Hiển thị mật khẩu");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword);

        jPanel14.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setPreferredSize(new java.awt.Dimension(265, 65));
        panelRound5.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên");
        panelRound5.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nameField.setMinimumSize(new java.awt.Dimension(65, 25));
        nameField.setPreferredSize(new java.awt.Dimension(65, 20));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        panelRound5.add(nameField, java.awt.BorderLayout.CENTER);

        panelRound9.add(panelRound5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(130, 65));
        jPanel8.setPreferredSize(new java.awt.Dimension(120, 65));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Lớp");
        jPanel8.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        classField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        classField.setPreferredSize(new java.awt.Dimension(0, 0));
        classField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classFieldActionPerformed(evt);
            }
        });
        jPanel8.add(classField, java.awt.BorderLayout.CENTER);

        panelRound9.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(150, 65));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(130, 65));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã sinh viên");
        jPanel7.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        msvField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        msvField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        msvField.setPreferredSize(new java.awt.Dimension(0, 0));
        msvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msvFieldActionPerformed(evt);
            }
        });
        jPanel7.add(msvField, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel7, "card2");

        panelRound9.add(jPanel9);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Ngày sinh");
        jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        birthField.setBackground(new java.awt.Color(255, 255, 255));
        birthField.setToolTipText("adasd");
        birthField.setDateFormatString("dd/MM/yyyy");
        birthField.setMinSelectableDate(new java.util.Date(-62135791115000L));
        birthField.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel3.add(birthField, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giới tính");
        jPanel4.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Nam");
        jRadioButton2.setActionCommand("nữ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton2);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Nữ");
        jRadioButton1.setActionCommand("nam");
        jRadioButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel4);

        panelRound9.add(jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(265, 65));
        jPanel11.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email");
        jPanel11.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        emailField.setPreferredSize(new java.awt.Dimension(65, 20));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel11.add(emailField, java.awt.BorderLayout.CENTER);

        panelRound9.add(jPanel11);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(265, 65));
        jPanel10.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ");
        jPanel10.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        addressField.setMinimumSize(new java.awt.Dimension(65, 25));
        addressField.setPreferredSize(new java.awt.Dimension(65, 20));
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel10.add(addressField, java.awt.BorderLayout.CENTER);

        panelRound9.add(jPanel10);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(265, 65));
        jPanel12.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");
        jPanel12.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        phoneField.setPreferredSize(new java.awt.Dimension(65, 20));
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        jPanel12.add(phoneField, java.awt.BorderLayout.CENTER);

        panelRound9.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(265, 65));
        jPanel13.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Mật khẩu");
        jPanel13.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        passwordField.setPreferredSize(new java.awt.Dimension(65, 20));
        jPanel13.add(passwordField, java.awt.BorderLayout.CENTER);

        panelRound9.add(jPanel13);

        jPanel14.add(panelRound9, java.awt.BorderLayout.CENTER);

        panelRound2.add(jPanel14, "card2");

        panelRound6.add(panelRound2, "card2");

        panelRound1.add(panelRound6, java.awt.BorderLayout.CENTER);

        panelRound7.add(panelRound1, "card2");

        getContentPane().add(panelRound7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void msvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msvFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msvFieldActionPerformed

    private void classFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void panelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseClicked
        //validate
        if(validateFormSignUp()){
            //create user
            User user = new User();
            UserDAO userDAO = new UserDAO();
            
            char[] passwordChars = passwordField.getPassword();
            String password = new String(passwordChars);
            user.setUsername(msvField.getText().strip().toUpperCase());
            user.setPassword(password);
            user.setIsAdmin(false);
            
            Student student = new Student();
            StudentDAO studentDAO = new StudentDAO();
            
            student.setName(nameField.getText().strip().toUpperCase());
            student.setBirthday(new SimpleDateFormat("dd/MM/yyyy").format(birthField.getDate()));
            student.setId(msvField.getText().strip().toUpperCase());
            student.setAddress(addressField.getText().strip().toUpperCase());
            student.setEmail(emailField.getText().strip());
            if(buttonGroup1.getSelection().getActionCommand().equalsIgnoreCase("nam")){
                student.setGender(false);
            }else{
                student.setGender(true);
            }
            student.setClassName(classField.getText().strip().toUpperCase());
            student.setPhoneNumber(phoneField.getText().strip());
            
            if(userDAO.createUser(user) == 1 && studentDAO.createStudent(student) == 1){
                new SuceessfulSignUp(this, true).setVisible(true);
               this.dispose();
            }
            

            
            
            
            //create student
            
            student.setName(password);
             
            
        }else{
            shakeDialog(this);
        }


        //create account
        
        
       
    }//GEN-LAST:event_panelRound3MouseClicked

    private void panelRound4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_panelRound4MouseClicked

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if(showPassword.isSelected()){
            passwordField.setEchoChar((char) 0);
        } else {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void shakeDialog(JDialog dialog) {
        int originalX = dialog.getX();
        int shakeDistance = 5; // Khoảng cách di chuyển khi rung rung

        Timer timer = new Timer(50, new ActionListener() {
            int shakeCount = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (shakeCount % 2 == 0) {
                    dialog.setLocation(dialog.getX() + shakeDistance, dialog.getY());
                } else {
                    dialog.setLocation(dialog.getX() - shakeDistance, dialog.getY());
                }

                shakeCount++;

                if (shakeCount >= 10) {
                    // Dừng timer khi đạt số lần rung cần thiết
                    ((Timer) e.getSource()).stop();
                    dialog.setLocation(originalX, dialog.getY());
                }
            }
        });
        timer.start();

        // Hiển thị JDialog
        dialog.setVisible(true);
    }
    private boolean validateFormSignUp(){
        char[] passwordChars = passwordField.getPassword();
        String password = new String(passwordChars);
        if(nameField.getText().strip() == "" || msvField.getText().strip() == "" 
                || birthField.getDate() == null ||buttonGroup1.getSelection() == null 
                ||classField.getText().strip() == "" || addressField.getText().strip() == "" 
                ||emailField.getText().strip() == "" || phoneField.getText().strip() == ""
                || password == "" || password == null){
            warnLabel.setText("Vui lòng nhập đầy đủ thông tin!");
            return false;
        }
        if(nameField.getText().length() < 5 ||msvField.getText().length() < 5 || password.length() < 5){
            warnLabel.setText("Họ và tên, Mã sinh viên và Mật khẩu phải trên 5 kí tự!");
            return false;
        }
        
        if(!emailField.getText().contains("@gmail.com")){
            if (!emailField.getText().contains("@student.ptithcm.edu.vn")){
                warnLabel.setText("Email không hợp lệ!(@gmail.com hoặc @student.ptithcm.edu.vn)!");
                return false;
            }
        }
        if(phoneField.getText().length() != 10 || !isNumeric(phoneField.getText())){
            warnLabel.setText("Số điện thoại không hợp lệ!(0-9)");
            return false;
        }
        StudentDAO studentDAO = new StudentDAO();
        List<Student> liStudent = studentDAO.getAll();
        if(exitEmail(liStudent, emailField.getText().strip())){
            warnLabel.setText("Email này đã được sử dụng");
            return false;
        }
        if(exitPhone(liStudent, phoneField.getText().strip())){
            warnLabel.setText("Số điện thoại này đã được sử dụng");
            return false;
        }
        if(exitUsername(liStudent, msvField.getText().strip())){
            warnLabel.setText("Mã sinh viên này đã tồn tại!");
            return false;
        }
        return true;
    }
    
    
    public static boolean isNumeric(String str) {
    if (str == null)
        return false;
    for (char c : str.toCharArray())
        if (c < '0' || c > '9')
            return false;
    return true;
    }
    private boolean exitEmail(List<Student> li, String email){
        for (Student st : li){
            if(st.getEmail().compareToIgnoreCase(email) == 0){
                return true;
            }
        }
        return false;
    }
    private boolean exitUsername(List<Student> li, String username){
        for (Student st : li){
            if(st.getId().compareToIgnoreCase(username) == 0){
                return true;
            }
        }
        return false;
    }
    
    private boolean exitPhone(List<Student> li, String phone){
        for (Student st : li){
//            if(st.getPhoneNumber().compareToIgnoreCase(phone) == 0){
//                return true;
//            }
              System.out.println(st.getPhoneNumber());
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignupDialog dialog = new SignupDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private com.toedter.calendar.JDateChooser birthField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField classField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField msvField;
    private javax.swing.JTextField nameField;
    private Handle.PanelRound panelRound1;
    private Handle.PanelRound panelRound2;
    private Handle.PanelRound panelRound3;
    private Handle.PanelRound panelRound4;
    private Handle.PanelRound panelRound5;
    private Handle.PanelRound panelRound6;
    private Handle.PanelRound panelRound7;
    private Handle.PanelRound panelRound9;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel warnLabel;
    // End of variables declaration//GEN-END:variables
}
